// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/RusselRustCode/teacher_analytics/core-service/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AnalyticsService is an autogenerated mock type for the AnalyticsService type
type AnalyticsService struct {
	mock.Mock
}

// GetAnalytics provides a mock function with given fields: ctx, studentID
func (_m *AnalyticsService) GetAnalytics(ctx context.Context, studentID uint64) (*domain.StudentAnalytics, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalytics")
	}

	var r0 *domain.StudentAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*domain.StudentAnalytics, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *domain.StudentAnalytics); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudentAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentByID provides a mock function with given fields: ctx, id
func (_m *AnalyticsService) GetStudentByID(ctx context.Context, id uint64) (*domain.Student, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentByID")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*domain.Student, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *domain.Student); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentLogs provides a mock function with given fields: ctx, studentID, from, to
func (_m *AnalyticsService) GetStudentLogs(ctx context.Context, studentID uint64, from time.Time, to time.Time) ([]*domain.StudentLog, error) {
	ret := _m.Called(ctx, studentID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentLogs")
	}

	var r0 []*domain.StudentLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, time.Time, time.Time) ([]*domain.StudentLog, error)); ok {
		return rf(ctx, studentID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, time.Time, time.Time) []*domain.StudentLog); ok {
		r0 = rf(ctx, studentID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StudentLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, time.Time, time.Time) error); ok {
		r1 = rf(ctx, studentID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudents provides a mock function with given fields: ctx
func (m *AnalyticsService) GetStudents(ctx context.Context) ([]uint64, error) {
    args := m.Called(ctx)
    
    var r0 []uint64
    if rf, ok := args.Get(0).(func(context.Context) []uint64); ok {
        r0 = rf(ctx)
    } else {
        if args.Get(0) != nil {
            r0 = args.Get(0).([]uint64)
        }
    }

    var r1 error
    if rf, ok := args.Get(1).(func(context.Context) error); ok {
        r1 = rf(ctx)
    } else {
        r1 = args.Error(1)
    }

    return r0, r1
}

// SendLog provides a mock function with given fields: ctx, log
func (_m *AnalyticsService) SendLog(ctx context.Context, log *domain.StudentLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for SendLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StudentLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TriggerAnalysis provides a mock function with given fields: ctx, studentID
func (_m *AnalyticsService) TriggerAnalysis(ctx context.Context, studentID uint64) error {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for TriggerAnalysis")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, studentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAnalyticsService creates a new instance of AnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsService {
	mock := &AnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
