// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/RusselRustCode/teacher_analytics/core-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// AnalyticsClient is an autogenerated mock type for the AnalyticsClient type
type AnalyticsClient struct {
	mock.Mock
}

// AnalyzeStudent provides a mock function with given fields: ctx, studentID
func (_m *AnalyticsClient) AnalyzeStudent(ctx context.Context, studentID uint64) (*domain.StudentAnalytics, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeStudent")
	}

	var r0 *domain.StudentAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*domain.StudentAnalytics, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *domain.StudentAnalytics); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudentAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Close provides a mock function with no fields
func (_m *AnalyticsClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *AnalyticsClient) HealthCheck(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAnalyticsClient creates a new instance of AnalyticsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsClient {
	mock := &AnalyticsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
