// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MessageProducer is an autogenerated mock type for the MessageProducer type
type MessageProducer struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *MessageProducer) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Send provides a mock function with given fields: ctx, topic, key, value
func (_m *MessageProducer) Send(ctx context.Context, topic string, key []byte, value []byte) error {
	ret := _m.Called(ctx, topic, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, []byte) error); ok {
		r0 = rf(ctx, topic, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendJSON provides a mock function with given fields: ctx, topic, data
func (_m *MessageProducer) SendJSON(ctx context.Context, topic string, data interface{}) error {
	ret := _m.Called(ctx, topic, data)

	if len(ret) == 0 {
		panic("no return value specified for SendJSON")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, topic, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMessageProducer creates a new instance of MessageProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageProducer {
	mock := &MessageProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
