// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/RusselRustCode/teacher_analytics/core-service/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *Repository) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAnalyticsByStudentID provides a mock function with given fields: ctx, studentID
func (_m *Repository) GetAnalyticsByStudentID(ctx context.Context, studentID uint64) (*domain.StudentAnalytics, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalyticsByStudentID")
	}

	var r0 *domain.StudentAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*domain.StudentAnalytics, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *domain.StudentAnalytics); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudentAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLogsByMaterialID provides a mock function with given fields: ctx, materialID
func (_m *Repository) GetLogsByMaterialID(ctx context.Context, materialID string) ([]*domain.StudentLog, error) {
	ret := _m.Called(ctx, materialID)

	if len(ret) == 0 {
		panic("no return value specified for GetLogsByMaterialID")
	}

	var r0 []*domain.StudentLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.StudentLog, error)); ok {
		return rf(ctx, materialID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.StudentLog); ok {
		r0 = rf(ctx, materialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StudentLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, materialID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLogsByStudentID provides a mock function with given fields: ctx, studentID, from, to
func (_m *Repository) GetLogsByStudentID(ctx context.Context, studentID uint64, from time.Time, to time.Time) ([]*domain.StudentLog, error) {
	ret := _m.Called(ctx, studentID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetLogsByStudentID")
	}

	var r0 []*domain.StudentLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, time.Time, time.Time) ([]*domain.StudentLog, error)); ok {
		return rf(ctx, studentID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, time.Time, time.Time) []*domain.StudentLog); ok {
		r0 = rf(ctx, studentID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StudentLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, time.Time, time.Time) error); ok {
		r1 = rf(ctx, studentID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetStudentByID(ctx context.Context, id uint64) (*domain.Student, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentByID")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*domain.Student, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *domain.Student); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudents provides a mock function with given fields: ctx
func (_m *Repository) GetStudents(ctx context.Context) ([]*domain.Student, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStudents")
	}

	var r0 []*domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Student, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Student); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAnalytics provides a mock function with given fields: ctx, analytics
func (_m *Repository) SaveAnalytics(ctx context.Context, analytics *domain.StudentAnalytics) error {
	ret := _m.Called(ctx, analytics)

	if len(ret) == 0 {
		panic("no return value specified for SaveAnalytics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StudentAnalytics) error); ok {
		r0 = rf(ctx, analytics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveLog provides a mock function with given fields: ctx, log
func (_m *Repository) SaveLog(ctx context.Context, log *domain.StudentLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for SaveLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StudentLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveStudent provides a mock function with given fields: ctx, student
func (_m *Repository) SaveStudent(ctx context.Context, student *domain.Student) error {
	ret := _m.Called(ctx, student)

	if len(ret) == 0 {
		panic("no return value specified for SaveStudent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Student) error); ok {
		r0 = rf(ctx, student)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAnalytics provides a mock function with given fields: ctx, analytics
func (_m *Repository) UpdateAnalytics(ctx context.Context, analytics *domain.StudentAnalytics) error {
	ret := _m.Called(ctx, analytics)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAnalytics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StudentAnalytics) error); ok {
		r0 = rf(ctx, analytics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
