// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/analytics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     uint64                 `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeStudentRequest) Reset() {
	*x = AnalyzeStudentRequest{}
	mi := &file_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeStudentRequest) ProtoMessage() {}

func (x *AnalyzeStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeStudentRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeStudentRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeStudentRequest) GetStudentId() uint64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

type AnalyzeStudentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StudentId       uint64                 `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Cluster         string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	EngagementScore int32                  `protobuf:"varint,3,opt,name=engagement_score,json=engagementScore,proto3" json:"engagement_score,omitempty"`
	SuccessRate     float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	TopicEfficiency map[string]float64     `protobuf:"bytes,5,rep,name=topic_efficiency,json=topicEfficiency,proto3" json:"topic_efficiency,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Recommendations []string               `protobuf:"bytes,6,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	AnalyzedAt      string                 `protobuf:"bytes,7,opt,name=analyzed_at,json=analyzedAt,proto3" json:"analyzed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeStudentResponse) Reset() {
	*x = AnalyzeStudentResponse{}
	mi := &file_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeStudentResponse) ProtoMessage() {}

func (x *AnalyzeStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeStudentResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeStudentResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeStudentResponse) GetStudentId() uint64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *AnalyzeStudentResponse) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *AnalyzeStudentResponse) GetEngagementScore() int32 {
	if x != nil {
		return x.EngagementScore
	}
	return 0
}

func (x *AnalyzeStudentResponse) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *AnalyzeStudentResponse) GetTopicEfficiency() map[string]float64 {
	if x != nil {
		return x.TopicEfficiency
	}
	return nil
}

func (x *AnalyzeStudentResponse) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *AnalyzeStudentResponse) GetAnalyzedAt() string {
	if x != nil {
		return x.AnalyzedAt
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BatchAnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentIds    []uint64               `protobuf:"varint,1,rep,packed,name=student_ids,json=studentIds,proto3" json:"student_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAnalyzeRequest) Reset() {
	*x = BatchAnalyzeRequest{}
	mi := &file_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAnalyzeRequest) ProtoMessage() {}

func (x *BatchAnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAnalyzeRequest.ProtoReflect.Descriptor instead.
func (*BatchAnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *BatchAnalyzeRequest) GetStudentIds() []uint64 {
	if x != nil {
		return x.StudentIds
	}
	return nil
}

type BatchAnalyzeResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Results       []*AnalyzeStudentResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAnalyzeResponse) Reset() {
	*x = BatchAnalyzeResponse{}
	mi := &file_proto_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAnalyzeResponse) ProtoMessage() {}

func (x *BatchAnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAnalyzeResponse.ProtoReflect.Descriptor instead.
func (*BatchAnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *BatchAnalyzeResponse) GetResults() []*AnalyzeStudentResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_proto_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"\x15proto/analytics.proto\x12\fanalytics.v1\"6\n" +
	"\x15AnalyzeStudentRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x04R\tstudentId\"\x94\x03\n" +
	"\x16AnalyzeStudentResponse\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x04R\tstudentId\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12)\n" +
	"\x10engagement_score\x18\x03 \x01(\x05R\x0fengagementScore\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\x12d\n" +
	"\x10topic_efficiency\x18\x05 \x03(\v29.analytics.v1.AnalyzeStudentResponse.TopicEfficiencyEntryR\x0ftopicEfficiency\x12(\n" +
	"\x0frecommendations\x18\x06 \x03(\tR\x0frecommendations\x12\x1f\n" +
	"\vanalyzed_at\x18\a \x01(\tR\n" +
	"analyzedAt\x1aB\n" +
	"\x14TopicEfficiencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"6\n" +
	"\x13BatchAnalyzeRequest\x12\x1f\n" +
	"\vstudent_ids\x18\x01 \x03(\x04R\n" +
	"studentIds\"V\n" +
	"\x14BatchAnalyzeResponse\x12>\n" +
	"\aresults\x18\x01 \x03(\v2$.analytics.v1.AnalyzeStudentResponseR\aresults2\x9a\x02\n" +
	"\x10AnalyticsService\x12[\n" +
	"\x0eAnalyzeStudent\x12#.analytics.v1.AnalyzeStudentRequest\x1a$.analytics.v1.AnalyzeStudentResponse\x12R\n" +
	"\vHealthCheck\x12 .analytics.v1.HealthCheckRequest\x1a!.analytics.v1.HealthCheckResponse\x12U\n" +
	"\fBatchAnalyze\x12!.analytics.v1.BatchAnalyzeRequest\x1a\".analytics.v1.BatchAnalyzeResponseB@Z>github.com/RusselRustCode/teacher_analytics/core-service/protob\x06proto3"

var (
	file_proto_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_proto_rawDescData []byte
)

func file_proto_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_proto_rawDescData
}

var file_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_analytics_proto_goTypes = []any{
	(*AnalyzeStudentRequest)(nil),  // 0: analytics.v1.AnalyzeStudentRequest
	(*AnalyzeStudentResponse)(nil), // 1: analytics.v1.AnalyzeStudentResponse
	(*HealthCheckRequest)(nil),     // 2: analytics.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 3: analytics.v1.HealthCheckResponse
	(*BatchAnalyzeRequest)(nil),    // 4: analytics.v1.BatchAnalyzeRequest
	(*BatchAnalyzeResponse)(nil),   // 5: analytics.v1.BatchAnalyzeResponse
	nil,                            // 6: analytics.v1.AnalyzeStudentResponse.TopicEfficiencyEntry
}
var file_proto_analytics_proto_depIdxs = []int32{
	6, // 0: analytics.v1.AnalyzeStudentResponse.topic_efficiency:type_name -> analytics.v1.AnalyzeStudentResponse.TopicEfficiencyEntry
	1, // 1: analytics.v1.BatchAnalyzeResponse.results:type_name -> analytics.v1.AnalyzeStudentResponse
	0, // 2: analytics.v1.AnalyticsService.AnalyzeStudent:input_type -> analytics.v1.AnalyzeStudentRequest
	2, // 3: analytics.v1.AnalyticsService.HealthCheck:input_type -> analytics.v1.HealthCheckRequest
	4, // 4: analytics.v1.AnalyticsService.BatchAnalyze:input_type -> analytics.v1.BatchAnalyzeRequest
	1, // 5: analytics.v1.AnalyticsService.AnalyzeStudent:output_type -> analytics.v1.AnalyzeStudentResponse
	3, // 6: analytics.v1.AnalyticsService.HealthCheck:output_type -> analytics.v1.HealthCheckResponse
	5, // 7: analytics.v1.AnalyticsService.BatchAnalyze:output_type -> analytics.v1.BatchAnalyzeResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_analytics_proto_init() }
func file_proto_analytics_proto_init() {
	if File_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_proto = out.File
	file_proto_analytics_proto_goTypes = nil
	file_proto_analytics_proto_depIdxs = nil
}
