# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\x0c\x61nalytics.v1\"+\n\x15\x41nalyzeStudentRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\x04\"\xa8\x02\n\x16\x41nalyzeStudentResponse\x12\x12\n\nstudent_id\x18\x01 \x01(\x04\x12\x0f\n\x07\x63luster\x18\x02 \x01(\t\x12\x18\n\x10\x65ngagement_score\x18\x03 \x01(\x05\x12\x14\n\x0csuccess_rate\x18\x04 \x01(\x01\x12S\n\x10topic_efficiency\x18\x05 \x03(\x0b\x32\x39.analytics.v1.AnalyzeStudentResponse.TopicEfficiencyEntry\x12\x17\n\x0frecommendations\x18\x06 \x03(\t\x12\x13\n\x0b\x61nalyzed_at\x18\x07 \x01(\t\x1a\x36\n\x14TopicEfficiencyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x14\n\x12HealthCheckRequest\"7\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\x13\x42\x61tchAnalyzeRequest\x12\x13\n\x0bstudent_ids\x18\x01 \x03(\x04\"M\n\x14\x42\x61tchAnalyzeResponse\x12\x35\n\x07results\x18\x01 \x03(\x0b\x32$.analytics.v1.AnalyzeStudentResponse2\x9a\x02\n\x10\x41nalyticsService\x12[\n\x0e\x41nalyzeStudent\x12#.analytics.v1.AnalyzeStudentRequest\x1a$.analytics.v1.AnalyzeStudentResponse\x12R\n\x0bHealthCheck\x12 .analytics.v1.HealthCheckRequest\x1a!.analytics.v1.HealthCheckResponse\x12U\n\x0c\x42\x61tchAnalyze\x12!.analytics.v1.BatchAnalyzeRequest\x1a\".analytics.v1.BatchAnalyzeResponseB@Z>github.com/RusselRustCode/teacher_analytics/core-service/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/RusselRustCode/teacher_analytics/core-service/proto'
  _globals['_ANALYZESTUDENTRESPONSE_TOPICEFFICIENCYENTRY']._loaded_options = None
  _globals['_ANALYZESTUDENTRESPONSE_TOPICEFFICIENCYENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZESTUDENTREQUEST']._serialized_start=33
  _globals['_ANALYZESTUDENTREQUEST']._serialized_end=76
  _globals['_ANALYZESTUDENTRESPONSE']._serialized_start=79
  _globals['_ANALYZESTUDENTRESPONSE']._serialized_end=375
  _globals['_ANALYZESTUDENTRESPONSE_TOPICEFFICIENCYENTRY']._serialized_start=321
  _globals['_ANALYZESTUDENTRESPONSE_TOPICEFFICIENCYENTRY']._serialized_end=375
  _globals['_HEALTHCHECKREQUEST']._serialized_start=377
  _globals['_HEALTHCHECKREQUEST']._serialized_end=397
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=399
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=454
  _globals['_BATCHANALYZEREQUEST']._serialized_start=456
  _globals['_BATCHANALYZEREQUEST']._serialized_end=498
  _globals['_BATCHANALYZERESPONSE']._serialized_start=500
  _globals['_BATCHANALYZERESPONSE']._serialized_end=577
  _globals['_ANALYTICSSERVICE']._serialized_start=580
  _globals['_ANALYTICSSERVICE']._serialized_end=862
# @@protoc_insertion_point(module_scope)
